# Generated by Django 2.2 on 2019-04-22 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=70)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UniversalUser',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('e_mail', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('n_mec', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('universal_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pi_django.UniversalUser')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=10)),
                ('time_stamp', models.DateTimeField()),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi_django.Credential')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='universal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pi_django.UniversalUser'),
        ),
        migrations.AddField(
            model_name='credential',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
