# Generated by Django 2.2 on 2019-04-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_django', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='start_time',
            field=models.DateField(blank=True),
        ),
    ]
