# Generated by Django 2.2 on 2019-04-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi_django', '0004_auto_20190415_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
